version: '3'
services: 
    secondkill-vue:
        build: 
            context: .
        image: secondkill-vue
        container_name: secondkill-vue
        restart: always
        ports: 
            - 80:80
        networks: 
            - secondkill_default
        external_links: 
            - secondkill-zuul

networks:
    secondkill_default:
        external: true   